DATA:
  dataset: refcoco
  train_lmdb: /data/zhanghuiyong/_DataSet/RefCoCo/lmdb/refcoco/train.lmdb
  train_split: train
  val_lmdb: /data/zhanghuiyong/_DataSet/RefCoCo/lmdb/refcoco/val.lmdb
  val_split: val
  mask_root: /data/zhanghuiyong/_DataSet/RefCoCo/masks/refcoco
TRAIN:
  # Base Arch
  clip_pretrain: pretrain/ViT-B-16.pt
  input_size: 416 # 224
  word_len: 17  # 17
  word_dim: 512
  vis_dim: 512
  num_phrase: 5    # __zhy__
  num_areas: 200    # __zhy__
  # Neck
  fpn_in: [768, 768, 512]
  fpn_out: [256, 512, 1024]
  sync_bn: True
  # Decoder
  num_layers: 3
  num_head: 8
  dim_ffn: 2048
  dropout: 0.1
  intermediate: False
  # Training Setting
  workers: 32  # data loader workers
  workers_val: 16
  epochs: 60
  milestones: [35]
  start_epoch: 0
  batch_size: 16  # batch size for training
  batch_size_val: 16  # batch size for validation during training, memory and speed tradeoff
  base_lr: 0.0001
  lr_decay: 0.1
  lr_multi: 0.1
  weight_decay: 0.
  max_norm: 0.
  manual_seed: 0
  print_freq: 100
  # Resume & Save
  exp_name: CRIS_ViT
  output_folder: exp/refcoco
  save_freq: 1
  weight:  # path to initial weight (default: none)
  resume:  # path to latest checkpoint (default: none)
  evaluate: True  # evaluate on validation set, extra gpu memory needed and small batch_size_val is recommend
Distributed:
  dist_url: tcp://localhost:3681
  dist_backend: 'nccl'
  multiprocessing_distributed: True
  world_size: 1
  rank: 0
TEST:
  test_split: val-test
  test_lmdb: /data/zhanghuiyong/_DataSet/RefCoCo/lmdb/refcoco/val.lmdb
  visualize: False